application: lightweight-django-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: blog.wsgi.application
  login: admin
  secure: always

- url: /static
  static_dir: sitestatic

# Set dashboard to be login:required
- url: /dashboard.*
  script: blog.wsgi.application
  secure: always
  login: required

- url: /.*
  script: blog.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - venv
    - blog/static
    - blog/dashboard/static
    - lib/google_appengine
    - (.*)\.pyc
